name:                hiddenmarkov-haskell
version:             1.0.0
github:              "nyando/hiddenmarkov-haskell"
license:             BSD3
author:              "Nicki Dorrmann"
maintainer:          "nicki.dorrmann@googlemail.com"
copyright:           "2022 Nicki Dorrmann"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/nyando/hiddenmarkov-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- random
- hspec

library:
  source-dirs: src

executables:
  hiddenmarkov-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hiddenmarkov-haskell

tests:
  hiddenmarkov-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hiddenmarkov-haskell
