name: Haskell CI

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: create release
        id: create_release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      
      - name: output Release URL file
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      
      - name: save Release URL file for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt
  
  build_artifact:
    needs: [create_release]
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }} / ${{ github.ref }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        cabal: ["3.6.2.0"]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.1"
        exclude:
          - os: macOS-latest
            ghc: 9.0.2
          - os: macOS-latest
            ghc: 8.10.7

          - os: windows-latest
            ghc: 9.0.2
          - os: windows-latest
            ghc: 8.10.7

    steps:
    - uses: actions/checkout@v2
    
    - uses: haskell/actions/setup@v1.2
      id: setup-haskell-cabal
      name: setup haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

    - name: freeze
      run: |
        cabal freeze
    
    - name: test
      run: |
        cabal test

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: build binary
      run: |
        mkdir dist
        cabal install --install-method=copy --overwrite-policy=always --installdir=dist
    
    - name: set binary path
      run: echo "BINARY_PATH=./dist/hiddenmarkov-haskell-exe" >> $GITHUB_ENV
    
    - if: matrix.os == 'windows-latest'
      name: set exe extension for windows release
      run: echo "BINARY_PATH=./dist/hiddenmarkov-haskell-exe.exe" >> $env:GITHUB_ENV
    
    - name: compress binary
      uses: svenstaro/upx-action@2.0.1
      with:
        file: ${{ env.BINARY_PATH }}
    
    - name: load release URL
      uses: actions/download-artifact@v1
      with:
        name: release_url
    
    - name: get release file name and upload URL
      id: get_release_info
      run: |
        echo "::set-output name=upload_url::$(cat release_url/release_url.txt)"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}
